"""
Kaggle Bundler Tool

Compiles the PHOENIX v3.1 project into a single executable script for Kaggle Kernels.
Resolves dependencies, strips relative imports, and packages everything into one file.

Usage:
    python tools/bundle_kaggle.py --output phoenix_v3_1_kaggle.py
"""

import os
import re
import argparse

# Dependency Order (Topological Sort)
# 1. Base Layers (SpatialMixer, Ops)
# 2. Advanced Layers (KAN, Spectral)
# 3. Model Assembly (PHOENIX v3.1)
# 4. Data Loaders (Legacy & True25D)
# 5. Training Script (Entry Point)

DEPENDENCIES = [
    "src/models/ops.py",  # Fixed path: was src/ops.py
    "src/models/spatial_mixer.py",
    "src/models/scout.py",
    "src/models/context_aggregator.py",
    "src/models/spectral_snake.py",
    "src/models/kan_ssm.py",
    "src/models/model_v3_1.py",
    "src/data/loader_legacy.py",
    "src/data/loader_true_2_5d.py",
    "train_phoenix_v3_1.py"  # Main script appends at the end
]

def read_file(path):
    """Reads file content."""
    with open(path, 'r', encoding='utf-8') as f:
        return f.read()

def clean_imports(content):
    """
    Removes relative imports that won't work in a single file.
    Example: `from src.models.spatial_mixer import SpatialMixer` -> REMOVED
    """
    lines = content.split('\n')
    cleaned_lines = []

    for line in lines:
        # Skip local project imports
        if line.strip().startswith("from src.") or line.strip().startswith("import src."):
            continue
        # Skip the main script's conditional import block for bundled classes
        if "from src.models.model_v3_1 import" in line:
            continue

        cleaned_lines.append(line)

    return '\n'.join(cleaned_lines)

def bundle(output_path):
    print(f"📦 Bundling PHOENIX v3.1 for Kaggle...")

    final_content = []

    # 1. Header
    final_content.append('"""')
    final_content.append('PHOENIX v3.1 - Single File Bundle')
    final_content.append('Generated by tools/bundle_kaggle.py')
    final_content.append('"""')
    final_content.append('import os')
    final_content.append('import sys')
    final_content.append('import math')
    final_content.append('import numpy as np')
    final_content.append('import tensorflow as tf')
    final_content.append('from tensorflow.keras import layers, models, callbacks, optimizers, losses, metrics')
    final_content.append('\n')

    # 2. Append Dependencies
    for dep in DEPENDENCIES:
        if not os.path.exists(dep):
            # Try finding it in research/data/loaders if it's the loader
            if "loader_true_2_5d.py" in dep:
                alt_path = "research/data/loaders/true_25d_loader.py"
                if os.path.exists(alt_path):
                    dep = alt_path
                else:
                    print(f"⚠ Warning: Could not find {dep}")
                    continue
            else:
                print(f"⚠ Warning: Could not find {dep}")
                continue

        print(f"  + Adding {dep}")
        content = read_file(dep)
        cleaned = clean_imports(content)

        final_content.append(f"\n# === SOURCE: {dep} ===\n")
        final_content.append(cleaned)

    # 3. Write Output
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(final_content))

    print(f"✅ Bundle created at: {output_path}")
    print(f"   Size: {os.path.getsize(output_path) / 1024:.2f} KB")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=str, default="phoenix_v3_1_kaggle.py")
    args = parser.parse_args()

    bundle(args.output)
